[partitions.efi]
device = ""                 # vdXY, sdXY, nvmeXnYpZ, etc...
bootloader_id = "archlinux"

[partitions.boot]
device = "" # vdXY, sdXY, nvmeXnYpZ, etc...

[partitions.root]
device = ""                 # vdXY, sdXY, nvmeXnYpZ, etc...
crypt_mapping = "cryptroot"
encryption = true
fs = "ext4"
password = ""

[system]
drive = ""                # vdX, sdX, nvmeXnY, etc...
arch_host = ""
arch_username = ""
arch_userpass = ""
aur_helper = "paru"
mirror_protocol = "https"
multilib = true
timezone = ""             # Europe/Moscow, etc...
connection_command = []   # command to connect to the network

[shadowsocks]
password = ""
server = ""

[live_cd]
installer_location = "."
profile = "releng"

[packages]
archiso = [
  "gdm",
  "gnome-control-center",
  "gnome-terminal",
  "gnome-backgrounds",    # wallpapers
  "networkmanager",       # gui for gnome
  "gedit",
  "code",
  "eog",                  # image viewer
  "firefox",
  "ffmpegthumbnailer",
  "git",
  "pacman-contrib",       # rankmirrors (remove and use builtin reflector?)
]
aur = []
flatpak = [
  "com.skype.Client",
  "com.valvesoftware.Steam",
  "net.ankiweb.Anki",
  "org.chromium.Chromium",
  "org.deluge_torrent.deluge",
  "org.filezillaproject.Filezilla",
  "org.gimp.GIMP",
  "org.gnome.eog",                  # image viewer
  "org.gnome.Extensions",
  "org.gnome.FileRoller",           # archive manager
  "org.kde.dolphin",                # file manager
  "org.libreoffice.LibreOffice",
  "org.mozilla.firefox",
  "org.remmina.Remmina",            # remote desktop
  "org.telegram.desktop",
  "org.videolan.VLC",               # video player
]
pacman = [
  "archiso",
  # "code", remove and use from aur?
  "ffmpegthumbnailer",
  "flatpak",
  "gdm",
  "git",
  "gnome-control-center",
  "gnome-software-packagekit-plugin", # pacman integration
  "gnome-terminal",
  "gnome-tweaks",
  "gvfs-google",
  "htop",
  "man",
  "neofetch",
  "networkmanager",                   # gui for gnome network
  "noto-fonts-emoji",                 # used by "serayuzgur.crates"
  "openssh",                          # ssh command
  "shadowsocks-libev",
  "sshfs",
  "virt-manager",
  "xdg-user-dirs-gtk",                # additional directories for users
  "zsh",
]
pacman_system = [
  "base",
  "dhcpcd",
  "grub",
  "linux-firmware",
  "linux",
  "neovim",
  "sudo",
]
vscode = [
  # extensions
  "humao.rest-client",          # do requests in .http files
  "eamodio.gitlens",            # git
  "ms-python.python",           # python
  "bungcip.better-toml",        # toml
  "rust-lang.rust",             # rust
  "serayuzgur.crates",          # rust
  "alexcvzz.vscode-sqlite",     # sqlite
  "coolbear.systemd-unit-file", # systemd
  # themes
  # kesmarag.vscode-precision-theme
  "robbowen.synthwave-vscode",
]
